import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { Activity, ArrowDownRight, ArrowUpRight, Bell, BookOpen, Bot, BrainCircuit, CheckCircle2, ChevronDown, ChevronRight, CircleHelp, Clock3, Code2, GitBranch, GitFork, Inbox, LayoutDashboard, LineChart, LoaderCircle, Menu, Network, Search, Settings, ShieldAlert, Sparkles, Users, X } from 'lucide-react'
import { normalizeRepoId, traceApi, type Brief, type Health, type Investigation, type Repository } from './api'

type View = 'dashboard' | 'inbox' | 'investigations' | 'repository' | 'security' | 'health' | 'forecast' | 'activity' | 'brief'
type Tone = 'high' | 'security' | 'medium' | 'low'

const navGroups = [
  { label: 'Overview', items: [['dashboard', 'Dashboard', LayoutDashboard], ['inbox', 'Inbox', Inbox]] },
  { label: 'Intelligence', items: [['investigations', 'Investigations', Search], ['repository', 'Repository', GitBranch], ['security', 'Security Watch', ShieldAlert]] },
  { label: 'Health', items: [['health', 'Health', Activity], ['forecast', 'Forecast', LineChart]] },
  { label: 'Automation', items: [['activity', 'Agent Activity', Bot], ['brief', 'Weekly Brief', BookOpen]] },
] as const

function toneFor(item: Investigation): Tone { if (item.security_sensitive) return 'security'; if (item.decision === 'escalate') return 'high'; if (item.decision === 'needs_more_info') return 'low'; return 'medium' }
function actionFor(item: Investigation) { return item.security_sensitive ? 'Security review' : item.decision === 'escalate' ? 'Escalate' : item.decision === 'needs_more_info' ? 'Request info' : item.decision === 'duplicate' ? 'Duplicate' : 'Monitor' }
function relativeDate(value?: string) { if (!value) return 'recently'; const date = new Date(value); if (Number.isNaN(date.getTime())) return value; const minutes = Math.max(1, Math.round((Date.now() - date.getTime()) / 60000)); return minutes < 60 ? `${minutes}m ago` : minutes < 1440 ? `${Math.round(minutes / 60)}h ago` : `${Math.round(minutes / 1440)}d ago` }
function statusText(value?: string) { return value?.replace(/_/g, ' ') || 'unknown' }
function StatusBadge({ tone, children }: { tone: Tone; children: string }) { return <span className={`badge badge-${tone}`}><span className="badge-dot" />{children}</span> }
function PageHeader({ title, subtitle, action }: { title: string; subtitle: string; action?: ReactNode }) { return <div className="page-header"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div> }
function EmptyState({ text }: { text: string }) { return <div className="empty-state"><CheckCircle2 size={18} /><span>{text}</span></div> }
function MetricCard({ label, value, change, direction = 'up', tone }: { label: string; value: string; change?: string; direction?: 'up' | 'down'; tone?: string }) { return <div className="metric-card"><div className="metric-label">{label}<CircleHelp size={14} /></div><strong className="metric-value">{value}</strong>{change && <span className={`metric-change ${tone ?? (direction === 'up' ? 'bad' : 'good')}`}>{direction === 'up' ? <ArrowUpRight size={14} /> : <ArrowDownRight size={14} />}{change}</span>}</div> }
function IssueRow({ item }: { item: Investigation }) { const tone = toneFor(item); const confidence = item.explanation?.confidence_percent ? `${item.explanation.confidence_percent}%` : '—'; return <div className="issue-row"><StatusBadge tone={tone}>{tone === 'security' ? 'Security' : tone === 'high' ? 'High' : tone === 'medium' ? 'Med' : 'Low'}</StatusBadge><span className="issue-id">#{item.issue_id ?? '—'}</span><div className="issue-copy"><strong>{item.title || 'Untitled issue'}</strong><span><b>Why:</b> {item.reason || item.explanation?.reasons?.[0] || 'Investigation completed.'}</span></div><span className={`action-pill action-${tone}`}>{actionFor(item)}</span><span className="confidence">{confidence}</span><span className="age"><Clock3 size={13} />{relativeDate(item.investigation_timeline?.[0]?.started_at)}</span></div> }
function MetricData({ health }: { health: Health }) { return <div className="metrics-grid"><MetricCard label="Open issues" value={String(health.open_issue_count ?? 0)} change={`${health.backlog_growth_rate ?? 0}% vs previous snapshot`} /><MetricCard label="Open pull requests" value={String(health.open_pr_count ?? 0)} change={`${health.pr_backlog_growth_rate ?? 0}% vs previous snapshot`} /><MetricCard label="Active contributors" value={String(health.active_contributor_count ?? 0)} change={`${health.health_dashboard?.active_contributors?.change_percent ?? 0}% vs previous snapshot`} direction="down" tone="good" /><div className="metric-card health-card"><div className="metric-label">Repository health<CircleHelp size={14} /></div><strong className="health-status">{statusText(health.health_status)}</strong><span className="muted">Composite score <b>{health.health_score ?? '—'}</b></span></div></div> }
function TrendCard({ title, value, change, history, color }: { title: string; value: string; change: string; history: Array<{ timestamp: string; open_issue_count: number }>; color: 'amber' | 'red' }) { const values = history.map((point) => point.open_issue_count); const max = Math.max(...values, 1); const min = Math.min(...values, 0); const path = values.map((point, index) => `${index * (92 / Math.max(values.length - 1, 1))},${94 - ((point - min) / Math.max(max - min, 1)) * 70}`).join(' '); return <div className="trend-card"><div className="trend-head"><div><span className="eyebrow">History</span><h3>{title}</h3></div><span className="muted">{history.length} snapshots</span></div><div className="trend-summary"><strong>{value}</strong><span className={color === 'red' ? 'red-text' : 'amber-text'}>{change}</span></div>{values.length > 1 ? <svg className={`sparkline ${color}`} viewBox="0 0 92 100" preserveAspectRatio="none"><polyline points={path} fill="none" /></svg> : <div className="empty-chart">More snapshots will build this trend.</div>}</div> }
function Dashboard({ health, inbox, onNavigate }: { health: Health; inbox: Investigation[]; onNavigate: (view: View) => void }) { return <><PageHeader title="Repository Overview" subtitle="Understand what needs attention and how the project is trending." /><MetricData health={health} /><section className="section attention-section"><div className="section-heading"><div><h2>Needs your attention</h2><p>Ranked by priority, confidence and recency.</p></div><button className="text-button" onClick={() => onNavigate('inbox')}>Open inbox <ChevronRight size={16} /></button></div>{inbox.length ? <div className="issue-list">{inbox.slice(0, 8).map((item, index) => <IssueRow key={`${item.issue_id}-${index}`} item={item} />)}</div> : <EmptyState text="No escalated issues are currently in the maintainer inbox." />}</section><div className="dashboard-columns"><TrendCard title="Issue backlog" value={String(health.open_issue_count ?? 0)} change={`${health.backlog_growth_rate ?? 0}%`} history={health.history ?? []} color="amber" /><TrendCard title="Maintainer response time" value={`${health.avg_response_time_hours ?? 0}h`} change={`${health.response_time_growth_rate ?? 0}%`} history={health.history ?? []} color="red" /></div></> }
function InboxView({ items }: { items: Investigation[] }) { return <><PageHeader title="Maintainer Inbox" subtitle="Only the repository activity that may require your attention." /><div className="filter-tabs"><button className="active">All <span>{items.length}</span></button><button>High priority</button><button>Security</button><button>Possible duplicate</button><button>Stale</button><button>Missing information</button></div><div className="inbox-search"><Search size={17} /><span>Search indexed investigations from the backend.</span><button>Sort: Priority <ChevronDown size={14} /></button></div>{items.length ? <div className="issue-list">{items.map((item, index) => <IssueRow key={`${item.issue_id}-${index}`} item={item} />)}</div> : <EmptyState text="The backend returned an empty inbox." />}</> }
function InvestigationsView({ items, status }: { items: Investigation[]; status: string }) { return <><PageHeader title="Investigations" subtitle={`All investigations executed by RepoGuardian agents. Current run: ${statusText(status)}.`} /><div className="filter-tabs"><button className="active">All</button><button>Running</button><button>Completed</button><button>Escalated</button></div><div className="table-card"><div className="table-head"><span>Issue / PR</span><span>Reason</span><span>Decision</span><span>Confidence</span></div>{items.length ? items.map((item, index) => <div className="investigation-row" key={`${item.issue_id}-${index}`}><a href={item.url} target="_blank" rel="noreferrer">#{item.issue_id}</a><strong>{item.title || 'Untitled issue'}</strong><span>{actionFor(item)}</span><span>{item.explanation?.confidence_percent ? `${item.explanation.confidence_percent}%` : '—'}</span></div>) : <EmptyState text="No investigation results are available for this repository yet." />}</div></> }
function RepositoryView({ repository }: { repository: Repository }) { return <><PageHeader title="Repository Intelligence" subtitle={repository.description || 'Live repository metadata from GitHub and the TRACE index.'} /><div className="view-tabs"><button className="active">Repository</button><button>Pull requests</button><button>Contributors</button><button>Code hotspots</button></div><div className="repo-stat-grid"><div><Code2 /><strong>{repository.commit_count ?? 0}</strong><span>Commits indexed</span></div><div><Users /><strong>{repository.language || 'Unknown'}</strong><span>Primary language</span></div><div><GitBranch /><strong>{repository.decisions}</strong><span>Rationale decisions</span></div></div></> }
function SecurityView({ items }: { items: Investigation[] }) { const security = items.filter((item) => item.security_sensitive); return <><PageHeader title="Security Watch" subtitle="Potentially security-sensitive activity flagged for human review." /><div className="notice"><ShieldAlert size={18} /><span>These items are flagged for review, not confirmed vulnerabilities. Always verify manually before taking public action.</span></div>{security.length ? <div className="security-list">{security.map((item, index) => <div className="security-card" key={`${item.issue_id}-${index}`}><div className="security-card-head"><div><span className="eyebrow">#{item.issue_id} &nbsp; Potentially security-sensitive</span><h2>{item.title}</h2><span className="muted">{actionFor(item)}</span></div><a className="outline-button" href={item.url} target="_blank" rel="noreferrer">Review issue <ChevronRight size={15} /></a></div><div className="signals"><div><span>Security signals</span><StatusBadge tone="security">Flagged</StatusBadge></div>{(item.explanation?.reasons ?? []).slice(0, 3).map((reason) => <div key={reason}><span>{reason}</span><StatusBadge tone="medium">Evidence</StatusBadge></div>)}</div></div>)}</div> : <EmptyState text="No security-sensitive issues were flagged in the latest scan." />}</> }
function HealthView({ health, forecast = false }: { health: Health; forecast?: boolean }) { const history = health.history ?? []; return <><PageHeader title={forecast ? 'Health Forecast' : 'Repository Health'} subtitle={forecast ? 'Project repository trajectory based on recent activity.' : 'Track whether repository activity is becoming healthier or harder to maintain.'} />{forecast ? <><div className="forecast-cards"><MetricCard label="Current" value={`${health.open_issue_count ?? 0} open issues`} /><MetricCard label="Next week projection" value={health.projected_backlog_next_week == null ? '—' : String(health.projected_backlog_next_week)} change={health.forecast_status ?? 'insufficient history'} tone="amber-text" /><MetricCard label="Forecast confidence" value={health.health_confidence ?? 'low'} change={health.projected_contributor_trend ?? 'No trend yet'} /></div><div className="forecast-chart"><div className="chart-title"><h2>Issue backlog forecast</h2><span>{health.forecast_status ?? 'insufficient history'}</span></div><TrendCard title="Projected backlog" value={String(health.open_issue_count ?? 0)} change={`${health.backlog_growth_rate ?? 0}%`} history={history} color="amber" /></div></> : <><div className="health-banner"><div><span className="eyebrow">Repository health</span><h2>{statusText(health.health_status)} <span>{health.health_confidence ?? 'low'} confidence</span></h2><p>{health.health_reasons?.[0]?.message || 'Health signals are calculated from the connected repository activity.'}</p></div><Activity size={30} /></div><MetricData health={health} /><div className="dashboard-columns"><TrendCard title="Issue backlog" value={String(health.open_issue_count ?? 0)} change={`${health.backlog_growth_rate ?? 0}%`} history={history} color="amber" /><TrendCard title="Activity window" value={`${health.avg_response_time_hours ?? 0}h`} change={`${health.response_time_growth_rate ?? 0}%`} history={history} color="red" /></div></>}</> }
function ActivityView({ items, status }: { items: Investigation[]; status: string }) { const latest = items[0]; return <><PageHeader title="Agent Activity" subtitle={`Live view of RepoGuardian's repository monitoring and investigations. Run status: ${statusText(status)}.`} action={<span className="live-indicator"><span /> {statusText(status)}</span>} />{latest ? <div className="activity-card"><div className="activity-top"><a href={latest.url} target="_blank" rel="noreferrer">Issue #{latest.issue_id}</a><strong>{latest.title}</strong><StatusBadge tone={toneFor(latest)}>{actionFor(latest)}</StatusBadge></div><div className="activity-detail"><div><span className="eyebrow">Investigation evidence</span>{(latest.investigation_timeline ?? []).map((step, index) => <p key={`${step.step}-${index}`}><CheckCircle2 size={15} />{step.label || step.step || 'Investigation step completed'}</p>)}</div><div><span className="eyebrow">Reason</span><p>{latest.reason || 'No reason returned.'}</p><span className="eyebrow">Confidence</span><strong>{latest.explanation?.confidence_percent ? `${latest.explanation.confidence_percent}%` : 'Not available'}</strong></div></div></div> : <EmptyState text="No agent investigation activity is available yet." />}</> }
function BriefView({ brief }: { brief: Brief }) { return <><PageHeader title="Weekly Brief" subtitle="A concise readout of repository health and maintainer priorities." action={<button className="primary-button"><Sparkles size={16} /> Generate brief</button>} /><div className="brief-grid"><div className="brief-main"><span className="eyebrow">Generated {relativeDate(brief.generated_at)}</span><h2>{brief.summary_text ? 'Repository brief' : 'No brief generated yet'}</h2><p>{brief.summary_text || 'The backend has not returned a weekly brief for this repository.'}</p><div className="brief-signature"><BrainCircuit size={18} />Generated by TRACE from repository health and activity data</div></div><div className="brief-side"><MetricCard label="Open issues" value={String(brief.raw_stats?.open_issue_count_this_week ?? '—')} /><MetricCard label="Previous snapshot" value={String(brief.raw_stats?.open_issue_count_last_week ?? '—')} /><MetricCard label="Scanned decisions" value={String(Object.values(brief.raw_stats?.decision_counts ?? {}).reduce((sum, value) => sum + value, 0))} /></div></div></> }

function Landing({ onStarted }: { onStarted: (repoId: string) => void }) { const [value, setValue] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); const repoId = normalizeRepoId(value); if (!repoId.includes('/') || repoId.split('/').some((part) => !part)) { setError('Enter a valid GitHub URL or owner/repository name.'); return } setLoading(true); setError(''); onStarted(repoId); } return <main className="landing"><div className="landing-top"><div className="brand"><div className="brand-mark"><ShieldAlert size={18} /></div><div><strong>RepoGuardian</strong><span>MAINTAINER OS</span></div></div><span className="landing-badge"><Sparkles size={14} /> TRACE decision intelligence</span></div><section className="landing-hero"><div className="hero-kicker"><span /> Repository intelligence for maintainers</div><h1>See what your repository is trying to tell you.</h1><p>Connect a GitHub repository to surface decisions, investigate issues, and understand whether project health is improving or drifting.</p><form onSubmit={submit} className="repo-form"><div><GitBranch size={18} /><input value={value} onChange={(event) => setValue(event.target.value)} placeholder="https://github.com/owner/repository" aria-label="Repository URL" /></div><button className="primary-button" disabled={loading}>{loading ? <LoaderCircle className="spin" size={16} /> : <ArrowUpRight size={16} />}{loading ? 'Starting scan...' : 'Trace repository'}</button></form>{error && <p className="form-error">{error}</p>}<div className="landing-note"><CheckCircle2 size={15} /> Your backend ingests GitHub activity and starts RepoGuardian monitoring.</div></section><div className="landing-features"><div><Bot size={19} /><strong>Issue investigations</strong><span>Prioritize work with evidence.</span></div><div><LineChart size={19} /><strong>Health trajectory</strong><span>See pressure signals over time.</span></div></div></main> }

export default function App() {
  const [repoId, setRepoId] = useState<string | null>(null); const [view, setView] = useState<View>('dashboard'); const [sidebarOpen, setSidebarOpen] = useState(false); const [loadState, setLoadState] = useState<'idle' | 'loading' | 'ready' | 'error'>('idle'); const [error, setError] = useState(''); const [health, setHealth] = useState<Health | null>(null); const [inbox, setInbox] = useState<Investigation[]>([]); const [investigations, setInvestigations] = useState<Investigation[]>([]); const [investigationStatus, setInvestigationStatus] = useState('not_started'); const [brief, setBrief] = useState<Brief>({}); const [repository, setRepository] = useState<Repository | null>(null);
  async function loadRepository(id: string) { setLoadState('loading'); setError(''); try { const [repo, healthData, inboxData, investigationsData, briefData] = await Promise.all([traceApi.repository(id), traceApi.health(id), traceApi.inbox(id), traceApi.investigations(id), traceApi.brief(id)]); setRepository(repo); setHealth(healthData); setInbox(inboxData.items ?? []); setInvestigations(investigationsData.investigations ?? []); setInvestigationStatus(investigationsData.status); setBrief(briefData); setLoadState('ready') } catch (err) { setError(err instanceof Error ? err.message : 'Could not load repository data.'); setLoadState('error') } }
  async function startRepository(id: string) { setRepoId(id); setView('dashboard'); setLoadState('loading'); try { await traceApi.ingest(id); let status = 'graphql'; for (let attempt = 0; attempt < 90 && status !== 'done'; attempt += 1) { await new Promise((resolve) => setTimeout(resolve, 2000)); status = (await traceApi.ingestStatus(id)).status; if (status.startsWith('error')) throw new Error(status) } await loadRepository(id) } catch (err) { setError(err instanceof Error ? err.message : 'Repository ingestion failed.'); setLoadState('error') } }
  useEffect(() => { if (repoId && loadState === 'ready') { const timer = window.setInterval(() => { traceApi.monitor(repoId).then((run) => { if (run.results?.investigations) setInvestigations(run.results.investigations) }).catch(() => undefined) }, 30000); return () => window.clearInterval(timer) } }, [repoId, loadState])
  const page = useMemo(() => { if (!health || !repository) return null; if (view === 'dashboard') return <Dashboard health={health} inbox={inbox} onNavigate={setView} />; if (view === 'inbox') return <InboxView items={inbox} />; if (view === 'investigations') return <InvestigationsView items={investigations} status={investigationStatus} />; if (view === 'repository') return <RepositoryView repository={repository} />; if (view === 'security') return <SecurityView items={investigations} />; if (view === 'health') return <HealthView health={health} />; if (view === 'forecast') return <HealthView health={health} forecast />; if (view === 'activity') return <ActivityView items={investigations} status={investigationStatus} />; return <BriefView brief={brief} /> }, [brief, health, inbox, investigationStatus, investigations, repository, view])
  if (!repoId) return <Landing onStarted={startRepository} />
  if (loadState === 'loading' && !health) return <div className="loading-screen"><LoaderCircle className="spin" size={28} /><h2>Building your repository view</h2><p>TRACE is ingesting GitHub activity and preparing the graph.</p><span>This can take a little while for a large repository.</span></div>
  if (loadState === 'error' && !health) return <div className="loading-screen"><ShieldAlert size={30} /><h2>Repository data could not be loaded</h2><p>{error}</p><button className="primary-button" onClick={() => loadRepository(repoId)}>Retry</button><button className="text-button" onClick={() => setRepoId(null)}>Choose another repository</button></div>
  return <div className="app-shell"><aside className={`sidebar ${sidebarOpen ? 'open' : ''}`}><div className="brand"><div className="brand-mark"><ShieldAlert size={18} /></div><div><strong>RepoGuardian</strong><span>MAINTAINER OS</span></div><button className="close-sidebar" onClick={() => setSidebarOpen(false)}><X size={18} /></button></div><div className="nav-scroll">{navGroups.map((group) => <div className="nav-group" key={group.label}><span className="nav-label">{group.label}</span>{group.items.map(([id, label, Icon]) => <button className={`nav-item ${view === id ? 'selected' : ''}`} key={id} onClick={() => { setView(id as View); setSidebarOpen(false) }}><Icon size={17} />{label}{id === 'inbox' && inbox.length > 0 && <span className="nav-count">{inbox.length}</span>}</button>)}</div>)}</div><div className="sidebar-footer"><div className="github-connect"><GitFork size={16} /><div><strong>GitHub connected</strong><span>{repoId}</span></div><i /></div><button className="nav-item" onClick={() => setRepoId(null)}><Settings size={17} />Change repository</button><div className="profile"><div className="avatar">TR</div><div><strong>TRACE maintainer</strong><span>connected workspace</span></div></div></div></aside><main className="main-area"><header className="topbar"><button className="menu-button" onClick={() => setSidebarOpen(true)}><Menu size={20} /></button><button className="repo-switcher"><GitBranch size={16} /><strong>{repoId}</strong><ChevronDown size={15} /></button><div className="monitoring"><span /> {investigationStatus === 'running' ? 'Monitoring active' : 'Monitoring ready'} <b>{repository?.language || 'Repository'}</b></div><div className="topbar-spacer" /><button className="global-search"><Search size={17} /><span>Search indexed decisions...</span><kbd>Ctrl K</kbd></button><button className="ask-button"><Sparkles size={16} /> Ask RepoGuardian</button><button className="icon-button"><Bell size={18} /></button><div className="top-avatar">TR</div></header><div className="content">{error && <div className="inline-error"><ShieldAlert size={15} />{error}</div>}{page}</div></main></div>
}
