/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepoRepoIdRouteImport } from './routes/repo.$repoId'
import { Route as ReposNewRouteImport } from './routes/repos.new'
import { Route as RepoRepoIdIndexRouteImport } from './routes/repo.$repoId.index'
import { Route as RepoRepoIdGuardianRouteImport } from './routes/repo.$repoId.guardian'
import { Route as RepoRepoIdHealthRouteImport } from './routes/repo.$repoId.health'
import { Route as RepoRepoIdRecallRouteImport } from './routes/repo.$repoId.recall'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRepoIdRoute = RepoRepoIdRouteImport.update({
  id: '/repo/$repoId',
  path: '/repo/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposNewRoute = ReposNewRouteImport.update({
  id: '/repos/new',
  path: '/repos/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRepoIdIndexRoute = RepoRepoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepoRepoIdRoute,
} as any)
const RepoRepoIdGuardianRoute = RepoRepoIdGuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => RepoRepoIdRoute,
} as any)
const RepoRepoIdHealthRoute = RepoRepoIdHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => RepoRepoIdRoute,
} as any)
const RepoRepoIdRecallRoute = RepoRepoIdRecallRouteImport.update({
  id: '/recall',
  path: '/recall',
  getParentRoute: () => RepoRepoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repo/$repoId': typeof RepoRepoIdRouteWithChildren
  '/repos/new': typeof ReposNewRoute
  '/repo/$repoId/guardian': typeof RepoRepoIdGuardianRoute
  '/repo/$repoId/health': typeof RepoRepoIdHealthRoute
  '/repo/$repoId/recall': typeof RepoRepoIdRecallRoute
  '/repo/$repoId/': typeof RepoRepoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/repos/new': typeof ReposNewRoute
  '/repo/$repoId/guardian': typeof RepoRepoIdGuardianRoute
  '/repo/$repoId/health': typeof RepoRepoIdHealthRoute
  '/repo/$repoId/recall': typeof RepoRepoIdRecallRoute
  '/repo/$repoId': typeof RepoRepoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/repo/$repoId': typeof RepoRepoIdRouteWithChildren
  '/repos/new': typeof ReposNewRoute
  '/repo/$repoId/guardian': typeof RepoRepoIdGuardianRoute
  '/repo/$repoId/health': typeof RepoRepoIdHealthRoute
  '/repo/$repoId/recall': typeof RepoRepoIdRecallRoute
  '/repo/$repoId/': typeof RepoRepoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/repo/$repoId'
    | '/repos/new'
    | '/repo/$repoId/guardian'
    | '/repo/$repoId/health'
    | '/repo/$repoId/recall'
    | '/repo/$repoId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/repos/new'
    | '/repo/$repoId/guardian'
    | '/repo/$repoId/health'
    | '/repo/$repoId/recall'
    | '/repo/$repoId'
  id:
    | '__root__'
    | '/'
    | '/repo/$repoId'
    | '/repos/new'
    | '/repo/$repoId/guardian'
    | '/repo/$repoId/health'
    | '/repo/$repoId/recall'
    | '/repo/$repoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RepoRepoIdRoute: typeof RepoRepoIdRouteWithChildren
  ReposNewRoute: typeof ReposNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$repoId': {
      id: '/repo/$repoId'
      path: '/repo/$repoId'
      fullPath: '/repo/$repoId'
      preLoaderRoute: typeof RepoRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/new': {
      id: '/repos/new'
      path: '/repos/new'
      fullPath: '/repos/new'
      preLoaderRoute: typeof ReposNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$repoId/': {
      id: '/repo/$repoId/'
      path: '/'
      fullPath: '/repo/$repoId/'
      preLoaderRoute: typeof RepoRepoIdIndexRouteImport
      parentRoute: typeof RepoRepoIdRoute
    }
    '/repo/$repoId/guardian': {
      id: '/repo/$repoId/guardian'
      path: '/guardian'
      fullPath: '/repo/$repoId/guardian'
      preLoaderRoute: typeof RepoRepoIdGuardianRouteImport
      parentRoute: typeof RepoRepoIdRoute
    }
    '/repo/$repoId/health': {
      id: '/repo/$repoId/health'
      path: '/health'
      fullPath: '/repo/$repoId/health'
      preLoaderRoute: typeof RepoRepoIdHealthRouteImport
      parentRoute: typeof RepoRepoIdRoute
    }
    '/repo/$repoId/recall': {
      id: '/repo/$repoId/recall'
      path: '/recall'
      fullPath: '/repo/$repoId/recall'
      preLoaderRoute: typeof RepoRepoIdRecallRouteImport
      parentRoute: typeof RepoRepoIdRoute
    }
  }
}

interface RepoRepoIdRouteChildren {
  RepoRepoIdGuardianRoute: typeof RepoRepoIdGuardianRoute
  RepoRepoIdHealthRoute: typeof RepoRepoIdHealthRoute
  RepoRepoIdRecallRoute: typeof RepoRepoIdRecallRoute
  RepoRepoIdIndexRoute: typeof RepoRepoIdIndexRoute
}

const RepoRepoIdRouteChildren: RepoRepoIdRouteChildren = {
  RepoRepoIdGuardianRoute: RepoRepoIdGuardianRoute,
  RepoRepoIdHealthRoute: RepoRepoIdHealthRoute,
  RepoRepoIdRecallRoute: RepoRepoIdRecallRoute,
  RepoRepoIdIndexRoute: RepoRepoIdIndexRoute,
}

const RepoRepoIdRouteWithChildren = RepoRepoIdRoute._addFileChildren(
  RepoRepoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RepoRepoIdRoute: RepoRepoIdRouteWithChildren,
  ReposNewRoute: ReposNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
